innDeveloper.Northwind.MvcWebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using innDeveloper.Business.Abstract;
using innDeveloper.Northwind.Entities.Concrete;
using innDeveloper.Northwind.MvcWebUI.Models;
using innDeveloper.Northwind.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace innDeveloper.Northwind.MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartSessionServices _cartSessionServices;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(ICartSessionServices cartSessionServices, ICartService cartService, IProductService productService)
        {
            _cartSessionServices = cartSessionServices;
            _cartService = cartService;
            _productService = productService;
        }
        public ActionResult AddToCart(int productId)
        {
            var productToBeAdded = _productService.GetById(productId);
            var cart = _cartSessionServices.GetCart();
            _cartService.AddToCart(cart,productToBeAdded);
           
            _cartSessionServices.SetCart(cart);
            TempData.Add("message",
                String.Format("Your product, {0} , was succesfully added to the cart!", productToBeAdded.ProductName));
            return RedirectToAction("Index", "Product");
        }

        public ActionResult List()
        {
            var cart = _cartSessionServices.GetCart();
            CartSummaryViewModel model = new CartSummaryViewModel
            {
                Cart = cart
            };
            return View(model);
        }

        public ActionResult Remove(int productId)
        {
            var cart = _cartSessionServices.GetCart();
            _cartService.RemoveFromCart(cart,productId);
            _cartSessionServices.SetCart(cart);
            TempData.Add("message", String.Format("Your product was succesfully removed from the cart"));
            return RedirectToAction("List");
        }

        public ActionResult Complete()
        {
            var ShippingDetailsViewModel = new ShippingDetailsViewModel
            {
                ShippingDetails = new ShippingDetails()
            };
            return View(ShippingDetailsViewModel);
        }
        [HttpPost]
        public ActionResult Complete(ShippingDetails shippingDetails)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message", String.Format("Thank you {0}, you order is process", shippingDetails.FirstName));
            return View();
        }
    }
}

innDeveloper.Northwind.MvcWebUI/Views/Cart/Complete.cshtml
@model innDeveloper.Northwind.MvcWebUI.Models.ShippingDetailsViewModel
@{
    ViewBag.Title = "title";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Shpping Detail</h2>
<form asp-controller="Cart" asp-action="Complete" method="post">


    <div class="form-group">
        <label asp-for="ShippingDetails.FirstName"></label>
        <input asp-for="ShippingDetails.FirstName" class="form-control" placeholder="First Name" />
        <span asp-validation-for="ShippingDetails.FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.LastName"></label>
        <input asp-for="ShippingDetails.LastName" class="form-control" placeholder="Last Name" />
        <span asp-validation-for="ShippingDetails.LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.Address"></label>
        <input asp-for="ShippingDetails.Address" class="form-control" placeholder="Address" />
        <span asp-validation-for="ShippingDetails.Address"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.City"></label>
        <input asp-for="ShippingDetails.City" class="form-control" placeholder="City" />
        <span asp-validation-for="ShippingDetails.City"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.Age"></label>
        <input asp-for="ShippingDetails.Age" class="form-control" placeholder="Age" />
        <span asp-validation-for="ShippingDetails.Age"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.Email"></label>
        <input asp-for="ShippingDetails.Email" class="form-control" placeholder="Email" />
        <span asp-validation-for="ShippingDetails.Email"></span>
    </div>
    <input type="submit" value="Complete Shopping " class="btn btn-xs btn-success" />

</form>

innDeveloper.Northwind.MvcWebUI/Views/Cart/List.cshtml
@model innDeveloper.Northwind.MvcWebUI.Models.CartSummaryViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>title</h2>
<table class="table">
    <tr>
        <td>Product Name</td>
        <td>Unit Price</td>
        <td>Units In Stock</td>
        <td>Quantity</td>
        <td></td>
    </tr>
    @foreach (var item in Model.Cart.CartLines)
    {
        <tr>
            <td>@item.Product.ProductName</td>
            <td>@item.Product.UnitPrice</td>
            <td>@item.Product.UnitsInStock</td>
            <td>@item.Quantity</td>
            <td class="text-right"><a class="btn btn-xs btn-danger" asp-controller="Cart" asp-action="Remove" asp-route-productId="@item.Product.ProductId"> <span class="glyphicon glyphicon-remove"></span>Remove From Cart</a></td>
        </tr>
    }
    
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><h3>Total</h3></td>
        <td class="text-right">
            <h3>
                <strong>@Model.Cart.Total</strong>
            </h3>
        </td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <a asp-controller="Product" asp-action="Index" class="btn btn-xs btn-default">
                <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping

            </a>
            
        </td>
        <td>
            <a asp-controller="Cart" asp-action="Complete" class="btn btn-xs btn-success">
                <span class="glyphicon glyphicon-shopping-play "></span>Go to Checkout
            </a>
        </td>
        </tr>
</table>